# Generated by Django 4.2.1 on 2023-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_created', models.DateField()),
                ('receipt', models.CharField(max_length=32)),
                ('payment_methods', models.CharField(max_length=32)),
            ],
        ),
    ]
