# Generated by Django 4.2.1 on 2023-06-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=32)),
                ('customer_name', models.CharField(max_length=32)),
                ('phonenumber', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
